version: '2'
services:
  sam_register_db:
    image: mysql
    ports:
      - "8812:8812"
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: arqsoft
      MYSQL_PASSWORD: 123
      MYSQL_DATABASE: users
      MYSQL_HOST: sam_register_db
  sam_register_ms:
    build: .
    command: bash -c "sleep 40 && rm -f tmp/pids/server.pid && bundle exec rails db:migrate && bundle exec rails s -p 3004 -b '0.0.0.0'"
    ports:
      - "3004:3004"
    depends_on:
      - sam_register_db
