version: '2'

services:
  sam_notifications_db:
    image: postgres
    ports:
      - "8810:5432"
    environment:
      POSTGRES_ROOT_PASSWORD: 1234
      POSTGRES_USER: notification
      POSTGRES_PASSWORD: 1234
      POSTGRES_DATABASE: notifications_db
      POSTGRES_HOST: sam_notifications_db
  sam_notifications_ms:
    build: .
    command: bash -c "sleep 40 && rm -f tmp/pids/server.pid && bundle exec rails db:migrate && bundle exec rails s -p 3003 -b '0.0.0.0'"
    ports:
      - "3003:3003"
    depends_on:
      - sam_notifications_db
