version: '2'
services:
  sam_sessions_db:
    image: mysql
    ports:
      - "8814:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: arqsoft
      MYSQL_PASSWORD: 123
      MYSQL_DATABASE: sessions
      MYSQL_HOST: sam_sessions_db
  sam_sessions_ms:
    build: .
    ports:
      - "3005:3005"
    depends_on:
      - sam_sessions_db
